### ISSUE TITLE
[CLI] print_config not showing correct callbacks

### ISSUE THREAD

**Issue by semaphore-egg** [PyTorchLightning/pytorch-lightning#11252]
## 🐛 Bug

[CLI] print_config not showing correct callbacks

### To Reproduce

running following command from root directory of pytorch-lightning (cloned from git origin master):
`python -m pl_examples.basic_examples.autoencoder --print_config`

Get `  callbacks: null`.
The full printed configs are:
```
seed_everything: 1234
trainer:
  logger: true
  checkpoint_callback: null
  enable_checkpointing: true
  callbacks: null
  default_root_dir: null
  gradient_clip_val: null
  gradient_clip_algorithm: null
  process_position: 0
  num_nodes: 1
  num_processes: 1
  devices: null
  gpus: null
  auto_select_gpus: false
  tpu_cores: null
  ipus: null
  log_gpu_memory: null
  progress_bar_refresh_rate: null
  enable_progress_bar: true
  overfit_batches: 0.0
  track_grad_norm: -1
  check_val_every_n_epoch: 1
  fast_dev_run: false
  accumulate_grad_batches: null
  max_epochs: 10
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  limit_predict_batches: 1.0
  val_check_interval: 1.0
  flush_logs_every_n_steps: null
  log_every_n_steps: 50
  accelerator: null
  strategy: null
  sync_batchnorm: false
  precision: 32
  enable_model_summary: true
  weights_summary: top
  weights_save_path: null
  num_sanity_val_steps: 2
  resume_from_checkpoint: null
  profiler: null
  benchmark: false
  deterministic: false
  reload_dataloaders_every_n_epochs: 0
  auto_lr_find: false
  replace_sampler_ddp: true
  detect_anomaly: false
  auto_scale_batch_size: false
  prepare_data_per_node: null
  plugins: null
  amp_backend: native
  amp_level: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
  stochastic_weight_avg: false
  terminate_on_nan: null
model:
  hidden_dim: 64
data:
  batch_size: 32
```

### Expected behavior

Should print correct callbacks related to `ImageSampler`.

### Environment

- PyTorch Lightning Version (1.5.6):
- PyTorch Version (1.10.1):
- Python version (3.8):
- OS (Ubuntu 20.04):
- CUDA/cuDNN version:
- GPU models and configuration:
- How you installed PyTorch (`pip`):
- If compiling from source, the output of `torch.__config__.show()`:
- Any other relevant information:

### Additional context

cc @carmocca @mauvilsa
