### ISSUE TITLE
LightningCLI: cannot set trainer args in default_config_files with run=True

### ISSUE THREAD

**Issue by tshu-w** [PyTorchLightning/pytorch-lightning#11991]
## 🐛 Bug

Trainer args settings in `default_config_files` will be ignore if `run=True` (subcommand enable).

### To Reproduce

1. `debug.py`:
```python
#!/usr/bin/env python
from pytorch_lightning.utilities.cli import LightningCLI

def main():
    cli = LightningCLI(
        parser_kwargs={
            "default_config_files": ["configs/config.yaml"],
        },
        run=True,
    )

if __name__ == "__main__":
    main()
```
2. `configs/config.yaml`:
```yaml
seed_everything: 123
fit:
  trainer:
    logger: false
```
3. run `python debug --print_config=skip_null fit` and get `logger: true`:
```
seed_everything: 123
fit:
  trainer:
    logger: true
    enable_checkpointing: true
    process_position: 0
    num_nodes: 1
    num_processes: 1
    auto_select_gpus: false
    enable_progress_bar: true
    overfit_batches: 0.0
    track_grad_norm: -1
    check_val_every_n_epoch: 1
    fast_dev_run: false
    max_steps: -1
    limit_train_batches: 1.0
    limit_val_batches: 1.0
    limit_test_batches: 1.0
    limit_predict_batches: 1.0
    val_check_interval: 1.0
    log_every_n_steps: 50
    sync_batchnorm: false
    precision: 32
    enable_model_summary: true
    weights_summary: top
    num_sanity_val_steps: 2
    benchmark: false
    deterministic: false
    reload_dataloaders_every_n_epochs: 0
    reload_dataloaders_every_epoch: false
    auto_lr_find: false
    replace_sampler_ddp: true
    detect_anomaly: false
    auto_scale_batch_size: false
    amp_backend: native
    move_metrics_to_cpu: false
    multiple_trainloader_mode: max_size_cycle
    stochastic_weight_avg: false
```

### Expected behavior

got:
```
seed_everything: 123
fit:
  trainer:
    logger: false
    enable_checkpointing: true
    process_position: 0
    num_nodes: 1
    num_processes: 1
    auto_select_gpus: false
    enable_progress_bar: true
    overfit_batches: 0.0
    track_grad_norm: -1
    check_val_every_n_epoch: 1
    fast_dev_run: false
    max_steps: -1
    limit_train_batches: 1.0
    limit_val_batches: 1.0
    limit_test_batches: 1.0
    limit_predict_batches: 1.0
    val_check_interval: 1.0
    log_every_n_steps: 50
    sync_batchnorm: false
    precision: 32
    enable_model_summary: true
    weights_summary: top
    num_sanity_val_steps: 2
    benchmark: false
    deterministic: false
    reload_dataloaders_every_n_epochs: 0
    reload_dataloaders_every_epoch: false
    auto_lr_find: false
    replace_sampler_ddp: true
    detect_anomaly: false
    auto_scale_batch_size: false
    amp_backend: native
    move_metrics_to_cpu: false
    multiple_trainloader_mode: max_size_cycle
    stochastic_weight_avg: false
```

### Environment

* Packages:
	- numpy:             1.22.2
	- pyTorch_debug:     False
	- pyTorch_version:   1.10.2+cu113
	- pytorch-lightning: 1.5.10
	- tqdm:              4.62.3
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- ELF
	- processor:         x86_64
	- python:            3.9.7
	- version:           #167-Ubuntu SMP Tue Sep 21 08:55:05 UTC 2021

### Additional context

This issue doesn't happen with CLI `run=False` or `python --config configs/config.yaml debug --print_config=skip_null fit`

cc @carmocca @mauvilsa
