### ISSUE TITLE
CLI data not working

### ISSUE THREAD

**Issue by AvivWn** [PyTorchLightning/pytorch-lightning#12229]
Hi

I'm trying to use LightningCLI object with yaml file that contains the parameters of a standard trainer and of my custom model and data modules.

The config yaml I defined:

```
trainer:
  callbacks:
    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        monitor: 'loss/val'
        patience: 5
        min_delta: 0.0
        mode: 'min'
    - class_path: project.callbacks.CheckpointEveryNSteps
      init_args:
        n_steps: 1000

model:
  class_path: project.models.TokenClassifier
  init_args:
    pretrained_model: &pretrained_model 'bert-base-uncased'
    out_dim: 15
    lr: 2e-5
    weight_decay: 2e-3
    dropout: 0.1

data:
  class_path: project.data_modules.TaggedTokensDataModule
  init_args:
    pretrained_model: *pretrained_model # ${fit.model.pretrained_model}
    batch_size: 256
    main_inputs_column: 'words'
    secondary_inputs_column: 'predicate'
    labels_column: 'labels'
```

When I run a trainer.py script that calls `LightningCLI(run=True)`, I keep getting the error:
`KeyError: 'Configuration check failed :: No action for destination key "data" to check its value.'`

What am I doing wrong?

cc @carmocca @mauvilsa
