### ISSUE TITLE
Dependency resolution not terminating when installing PL with Poetry

### ISSUE THREAD

**Issue by tillspeicher** [PyTorchLightning/pytorch-lightning#12549]
## 🐛 Bug

I am trying to install PL with Poetry as package manager. However, the Poetry's dependency resolution runs indefinitely (currently more than 20 minutes), and therefore installing PL is not possible.
Installing other packages (such as Pytorch) works fine, their dependencies are resolved quickly.

I saw some discussion [here](https://bleepcoder.com/poetry/571847205/poetry-is-extremely-slow-when-resolving-the-dependencies) regarding similar issues, and the takeaway seems to be that the packages where this happens for poetry don't properly and transitively specify dependency versions. Since poetry, in contrast to pip, tries to pin specific versions/version ranges, dependency resolution might fail or take very long in such cases.

I am not sure if this is the exact issue here, but it would be great if it was possible to use PL in conjunction with poetry.

### To Reproduce

1. Create an empty directory: `mkdir testproject && cd testproject`
2. Initialize Poetry, not changing any defaults and without specifying dependencies interactively: `poetry init`
3. Install Pytorch: `poetry add torch`. This executes normally for me.
4. Try to install PL: `poetry add pytorch-lightning`

The dependency resolution runs indefinitely now.

My `pyproject.toml` file prior to installing PL looks as follows:
```toml
[tool.poetry]
name = "testproject"
version = "0.1.0"
description = ""
authors = ["Me <me@example.com>"]

[tool.poetry.dependencies]
python = "^3.10"
torch = "^1.11.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

### Expected behavior

I expect poetry to quickly determine the required dependency versions, add them to the Lockfile (`poetry.lock`) and install PL.

### Environment

- PyTorch Lightning Version: latest/1.6.0
- PyTorch Version: 1.11.0
- Python version: 3.10.2
- OS: Manjaro Linux
- How you installed PyTorch: Poetry version 1.1.13
