### ISSUE TITLE
UserWarning: The flag devices=-1 will be ignored

### ISSUE THREAD

**Issue by mnslarcher** [PyTorchLightning/pytorch-lightning#12756]
## 🐛 Bug

I use this configuration Trainer(accelerator="gpu", devices=-1, auto_select_gpus=False) as suggested by the doc but I get:

UserWarning: The flag devices=-1 will be ignored, instead the device specific number 1

Even if on my AWS p3.x8large I have 4 GPUs:

[2022-03-31 10:29:41,160][pytorch_lightning.accelerators.gpu][INFO] - LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2,3]

### Expected behavior

All the GPUs are used.

### Environment

SageMaker Container: 763104351884.dkr.ecr.eu-central-1.amazonaws.com/pytorch-training:1.9.1-gpu-py38-cu111-ubuntu20.04
PyTorch Lightning Version 1.6.0
Python 3.8
NCCL version 2.7.8+cuda11.1

**Comment by awaelchli** [comment]
@mnslarcher Is it possible you used 

```py
Trainer(gpus=2, devices=-1, auto_select_gpus=False)
```

instead of what you wrote here? I can only reproduce it this way (did not run on sagemaker) and the warning would be appropriate here, because the numbers are conflicting each other. 

The usage
```py
Trainer(accelerator="gpu", devices=-1, auto_select_gpus=False)
```

is correct.

**Comment by mnslarcher** [comment]
You are right @awaelchli , to simplify (aka I'm using devices=-1 and the GPU accellerator) I leaved out details that maybe are important. No, I don't use gpu=2 or another number, in this moment I have gpu=None (null below because is a YAML).

I use Hydra, this is my full config, I didn't change gpus/accelerator/devices from the command line.

```
_target_: pytorch_lightning.Trainer
accelerator: auto
accumulate_grad_batches: null
amp_backend: native
amp_level: null
auto_lr_find: false
auto_scale_batch_size: false
auto_select_gpus: false
benchmark: false
callbacks: ${oc.dict.values:_callback_dict}
enable_checkpointing: true
check_val_every_n_epoch: 1
default_root_dir: ${checkpoints_dir}
detect_anomaly: false
deterministic: false
devices: -1
fast_dev_run: false
gpus: null
gradient_clip_algorithm: null
gradient_clip_val: null
limit_train_batches: 1.0
limit_val_batches: 1.0
limit_test_batches: 1.0
limit_predict_batches: 1.0
logger:
  _target_: pytorch_lightning.loggers.TensorBoardLogger
  save_dir: ${checkpoints_dir}/tb_logs
  name: ${experiment_name}
  version: null
  log_graph: false
  default_hp_metric: true
  prefix: ''
  sub_dir: null
log_every_n_steps: 50
profiler: null
overfit_batches: 0.0
enable_progress_bar: true
plugins: null
precision: 32
max_epochs: ${training.max_epochs}
min_epochs: null
max_steps: ${training.max_steps}
min_steps: null
max_time: null
num_nodes: 1
num_processes: 1
num_sanity_val_steps: 2
reload_dataloaders_every_n_epochs: 0
replace_sampler_ddp: true
strategy: null
sync_batchnorm: false
tpu_cores: null
ipus: null
track_grad_norm: -1
val_check_interval: 1.0
enable_model_summary: true
weights_save_path: null
move_metrics_to_cpu: false
multiple_trainloader_mode: max_size_cycle
```
