### ISSUE TITLE
Is there a way to make the Trainer skip loading optimizer from a checkpoint?

### ISSUE THREAD

**Issue by nihalsid** [PyTorchLightning/pytorch-lightning#1982]
Use case is if I want to load a model's weights but reset the the optimizer state. Is there a flag I can pass that skips loading the optimizer?

**Comment by awaelchli** [comment]
There is no flag but you could implement the model hook on_load_checkpoint and reset the optimizer yourself.

**Comment by nihalsid** [comment]
Cool thanks!

**Comment by kef-bassam** [comment]
> I think you can accomplish it this way without needing to know any of the optimizer's implementation details:
> 
> ```
>     # in your lightning module...
>     def on_load_checkpoint(self, checkpoint):
>         fresh_optimizer = Adam(...)
>         self.my_optimizer.load_state_dict(fresh_optimizer.state_dict())
> ```

If I wanted to reinstantiate the optimizer and scheduler using the yaml files and the Lightning CLI, is there a best way to do that?

The way that is mentioned above hardcodes the optimizer class within the Lightning Module but I'd like to limit all of my configuration and hyperparameter tuning through a `config.yaml` that I use with the CLI. I'm not sure how to expose the contents of the configuration file to the LightningModule though.

As an example: Config before finetuning 
```
data:
  class_path: OldDataModule
# ckpt_path: 
optimizer:
  class_path: torch.optim.SGD
  init_args:
    lr: 1e-03
lr_scheduler:
  class_path: torch.optim.lr_scheduler.StepLR
  init_args:
    step_size: 2 
    gamma: 0.90 
```

Config to use for finetuning:
```
data:
  class_path: NewDataModule
ckpt_path: ./logs/pretrained.ckpt
optimizer:
  class_path: torch.optim.SGD
  init_args:
    lr: 5e-08
lr_scheduler:
  class_path: torch.optim.lr_scheduler.ExponentialLR
  init_args:
    gamma: 0.10
```
