### ISSUE TITLE
Callbacks are not saved to the config file

### ISSUE THREAD

**Issue by tshu-w** [PyTorchLightning/pytorch-lightning#7540]
## 🐛 Bug

LightningCLI cannot save callbacks to config file.

## Please reproduce using the BoringModel
```shell
python train.py --print_config
# or
python train.py
# or
python train.py --config config.yaml # with config like this https://pytorch-lightning.readthedocs.io/en/latest/common/lightning_cli.html#trainer-callbacks-and-arguments-with-class-type
```

train.py: 
```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import os

import torch
from torch.utils.data import DataLoader, Dataset

from pytorch_lightning import LightningModule, Trainer
from pytorch_lightning.callbacks import EarlyStopping, ModelCheckpoint
from pytorch_lightning.utilities.cli import LightningCLI

class RandomDataset(Dataset):
    def __init__(self, size, length):
        self.len = length
        self.data = torch.randn(length, size)
    def __getitem__(self, index):
        return self.data[index]
    def __len__(self):
        return self.len

class BoringModel(LightningModule):
    def __init__(self):
        super().__init__()
        self.layer = torch.nn.Linear(32, 2)
    def forward(self, x):
        return self.layer(x)
    def training_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("train_loss", loss)
        return {"loss": loss}
    def validation_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("valid_loss", loss)
    def test_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("test_loss", loss)
    def configure_optimizers(self):
        return torch.optim.SGD(self.layer.parameters(), lr=0.1)
    def train_dataloader(self):
        return DataLoader(RandomDataset(32, 64), batch_size=2)
    def val_dataloader(self):
        return DataLoader(RandomDataset(32, 64), batch_size=2)
    def test_dataloader(self):
        return DataLoader(RandomDataset(32, 64), batch_size=2)

def run():
    early_stopping = EarlyStopping(monitor="valid_loss")
    checkpoint_callback = ModelCheckpoint(dirpath="logs", monitor="valid_loss")

    cli = LightningCLI(
        BoringModel,
        seed_everything_default=123,
        trainer_defaults={
            "max_epochs": 2,
            "callbacks": [
                checkpoint_callback,
                early_stopping,
            ],
            "logger": {
                "class_path": "pytorch_lightning.loggers.TestTubeLogger",
                "init_args": {
                    "save_dir": "logs",
                    "create_git_tag": True,
                },
            },
        },
    )
    cli.trainer.test(cli.model)

if __name__ == '__main__':
    run()
```

### Expected behavior

**Callbacks were saved to the config file. And should the logger and callbacks provided to `train_defaults` be of the same form?**

### Environment

```
* CUDA:
	- GPU:
		- TITAN RTX
		- TITAN RTX
		- TITAN RTX
		- TITAN RTX
		- TITAN RTX
		- TITAN RTX
		- TITAN RTX
		- TITAN RTX
		- TITAN RTX
		- TITAN RTX
	- available:         True
	- version:           10.2
* Packages:
	- numpy:             1.19.2
	- pyTorch_debug:     False
	- pyTorch_version:   1.8.1+cu102
	- pytorch-lightning: 1.3.1
	- tqdm:              4.50.2
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- ELF
	- processor:         x86_64
	- python:            3.8.5
	- version:           #146-Ubuntu SMP Tue Apr 13 01:11:19 UTC 2021
```

**Comment by awaelchli** [comment]
It cannot save the callbacks to the config file, because these are objects. You need to provide class path I believe. It is explained here: 
https://pytorch-lightning.readthedocs.io/en/latest/common/lightning_cli.html#trainer-callbacks-and-arguments-with-class-type

Basically, since you instantiate them yourself LightningCLI is unaware of them and doesn't know how to instantiate them. This does not just apply to callbacks.

**Comment by tshu-w** [comment]
> It cannot save the callbacks to the config file, because these are objects. You need to provide class path I believe. It is explained here:
> https://pytorch-lightning.readthedocs.io/en/latest/common/lightning_cli.html#trainer-callbacks-and-arguments-with-class-type

As I mention, I also tried `python train.py --config config.yaml --print_config` with `config.yaml` correctly set as the above link described. Callbacks settings still not print.

> Basically, since you instantiate them yourself LightningCLI is unaware of them and doesn't know how to instantiate them. This does not just apply to callbacks.

I have to instantiate them because I cannot pass them like logger like the following code. Should we handle callbacks the same way we handle loggers?
```python
cli = LightningCLI(
    BoringModel,
    seed_everything_default=123,
    trainer_defaults={
        "max_epochs": 2,
        "callbacks": [
            {
                "class_path": "pytorch_lightning.callbacks.ModelCheckpoint"
                "init_args": {
                    ...
                }
            },
        ],
        "logger": {
            "class_path": "pytorch_lightning.loggers.TestTubeLogger",
            "init_args": {
                "save_dir": "logs",
                "create_git_tag": True,
            },
        },
    },
)
```

**Comment by awaelchli** [comment]
Try this: 

```
seed_everything: 123
trainer:
  callbacks:
    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        patience: 5
        monitor: valid_loss
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        monitor: valid_loss
        dirpath: here

```

And then when we print the config it outputs everything: 
```
seed_everything: 123
trainer:
  logger: true
  checkpoint_callback: true
  callbacks:
  - class_path: pytorch_lightning.callbacks.EarlyStopping
    init_args:
      monitor: valid_loss
      min_delta: 0.0
      patience: 5
      verbose: false
      mode: min
      strict: true
      check_finite: true
      check_on_train_epoch_end: false
  - class_path: pytorch_lightning.callbacks.ModelCheckpoint
    init_args:
      dirpath: here
      monitor: valid_loss
      verbose: false
      save_weights_only: false
      mode: min
      auto_insert_metric_name: true
  default_root_dir: null
....
```


> I have to instantiate them because I cannot pass them like logger like the following code. Should we handle callbacks the same way we handle loggers?

Yes, I think the idea of jsonargparse is that we can instantiate any object like this.
