### ISSUE TITLE
TPU training is stuck at spawning using all 8-cores

### ISSUE THREAD

**Issue by mozharovsky** [PyTorchLightning/pytorch-lightning#7984]
## 🐛 Bug

Some transformer models from [🤗/transformers](https://github.com/huggingface/transformers) (namely, `t5` models) seem to stuck at the very beginning of the training process using all 8 TPU cores. This behavior is unusual since the same model works fine in a 1-core setup, and it also works fine using 8-cores via 🤗/Trainer.

I'm eager to figure out if this is 🤗/transformers issue or a Lightning bug.

## Please reproduce using the BoringModel

N/A

### To Reproduce

Please, use this Google Colab Notebook:
https://colab.research.google.com/drive/1FbWfkho3Otfl19y5ybkrK5Jw_tWNqV-M?usp=sharing

### Expected behavior

Training should work both for a 1-core and 8-cores setup.

### Environment

 - PyTorch Version (e.g., 1.0): 1.8.1+cu101
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source): No
 - Python version: 3.7.10
 - CUDA/cuDNN version: 10.1
 - GPU models and configuration: No
 - Any other relevant information: TPU v3

**Comment by kaushikb11** [comment]
Kind reminder: The effective batch size for 8 TPU cores is `batch_size * 8`

**Comment by mozharovsky** [comment]
@kaushikb11 thanks for replying! 

Yes, the effective batch size pays off in 1-core training. Nevertheless, the training is still stuck when using all 8 cores. The stack trace indicates that the process is stuck at multiprocess selector polling ([here](https://github.com/python/cpython/blob/769d7d0c66c5b86e2dd29b9ce67ac2daaab1bb38/Lib/selectors.py#L416)). Neither XLA metrics report indicates XLA devices utilization.

### XLA 8-cores training report:
```
Metric: XrtAllocateFromTensor
  TotalSamples: 15703
  Accumulator: 01m16s715ms407.010us
  Mean: 001ms404.163us
  StdDev: 004ms422.616us
  Rate: 48.5293 / second
  Percentiles: 25%=687.062us; 50%=885.794us; 80%=001ms209.382us; 90%=002ms794.029us; 95%=002ms965.974us; 99%=020ms190.586us
Metric: XrtCompile
  TotalSamples: 117
  Accumulator: 02m17s556ms203.744us
  Mean: 01s167ms147.041us
  StdDev: 04s855ms690.104us
  Rate: 0.0655334 / second
  Percentiles: 25%=004ms328.352us; 50%=006ms872.886us; 80%=266ms489.141us; 90%=01s099ms848.517us; 95%=16s074ms455.043us; 99%=17s824ms114.282us
Metric: XrtExecute
  TotalSamples: 2727
  Accumulator: 03m07s002ms412.511us
  Mean: 076ms733.329us
  StdDev: 085ms604.849us
  Rate: 1.15717 / second
  Percentiles: 25%=001ms467.541us; 50%=002ms010.422us; 80%=173ms626.149us; 90%=173ms956.923us; 95%=173ms187.526us; 99%=174ms633.142us
Metric: XrtExecutorEvict
  TotalSamples: 0
  Accumulator: nanB
  Mean: nanB
  StdDev: nanB
  Percentiles: 
Metric: XrtReadLiteral
  TotalSamples: 1417
  Accumulator: 885ms448.829us
  Mean: 625.785us
  StdDev: 159.260us
  Rate: 0.882739 / second
  Percentiles: 25%=523.011us; 50%=608.202us; 80%=769.035us; 90%=825.615us; 95%=863.824us; 99%=935.118us
Metric: XrtReleaseAllocation
  TotalSamples: 17330
  Accumulator: 07s777ms471.413us
  Mean: 342.848us
  StdDev: 453.037us
  Rate: 1.3637 / second
  Percentiles: 25%=027.749us; 50%=104.289us; 80%=685.053us; 90%=994.867us; 95%=001ms234.149us; 99%=002ms845.708us
```

### XLA 1-core training report:
```
Metric: CompileTime
  TotalSamples: 8
  Accumulator: 34s492ms852.692us
  ValueRate: 587ms040.144us / second
  Rate: 0.136157 / second
  Percentiles: 1%=002ms991.975us; 5%=002ms991.975us; 10%=002ms991.975us; 20%=009ms605.033us; 50%=280ms696.908us; 80%=14s918ms930.002us; 90%=15s077ms992.575us; 95%=15s077ms992.575us; 99%=15s077ms992.575us
Metric: DeviceLockWait
  TotalSamples: 497
  Accumulator: 006ms313.559us
  ValueRate: 097.910us / second
  Rate: 7.70745 / second
  Percentiles: 1%=001.149us; 5%=001.261us; 10%=001.347us; 20%=001.477us; 50%=001.988us; 80%=002.509us; 90%=002.818us; 95%=003.293us; 99%=016.114us
Metric: ExecuteTime
  TotalSamples: 496
  Accumulator: 18s559ms552.460us
  ValueRate: 273ms732.350us / second
  Rate: 7.70424 / second
  Percentiles: 1%=002ms384.278us; 5%=003ms676.282us; 10%=003ms778.325us; 20%=003ms955.749us; 50%=016ms781.256us; 80%=098ms495.746us; 90%=099ms165.846us; 95%=100ms764.174us; 99%=101ms560.489us
Metric: InboundData
  TotalSamples: 495
  Accumulator: 3.25KB
  ValueRate: 51.70B / second
  Rate: 7.69033 / second
  Percentiles: 1%=1.00B; 5%=1.00B; 10%=1.00B; 20%=1.00B; 50%=4.00B; 80%=4.00B; 90%=4.00B; 95%=4.00B; 99%=4.00B
Metric: InputOutputAliasCount
  TotalSamples: 4
  Accumulator: 1191.00
  ValueRate: 59.44 / second
  Rate: 0.199646 / second
  Percentiles: 1%=1.00; 5%=1.00; 10%=1.00; 20%=1.00; 50%=529.00; 80%=529.00; 90%=529.00; 95%=529.00; 99%=529.00
Metric: IrValueTensorToXlaData
  TotalSamples: 505
  Accumulator: 09s414ms142.674us
  ValueRate: 140ms818.311us / second
  Rate: 7.50023 / second
  Percentiles: 1%=001ms311.834us; 5%=001ms446.555us; 10%=002ms535.437us; 20%=002ms645.151us; 50%=002ms999.419us; 80%=024ms104.210us; 90%=045ms584.829us; 95%=088ms107.622us; 99%=090ms902.418us
Metric: OutboundData
  TotalSamples: 1046
  Accumulator: 549.85MB
  ValueRate: 6.86MB / second
  Rate: 15.293 / second
  Percentiles: 1%=4.00B; 5%=4.00B; 10%=4.00B; 20%=4.00B; 50%=32.00B; 80%=1.00MB; 90%=2.00MB; 95%=2.00MB; 99%=4.00MB
Metric: ReleaseDataHandlesTime
  TotalSamples: 3638
  Accumulator: 06s015ms321.957us
  ValueRate: 158ms694.793us / second
  Rate: 125.842 / second
  Percentiles: 1%=648.632us; 5%=749.156us; 10%=814.992us; 20%=891.265us; 50%=001ms066.041us; 80%=001ms406.205us; 90%=002ms697.375us; 95%=002ms914.948us; 99%=002ms278.051us
Metric: TensorsGraphSize
  TotalSamples: 496
  Accumulator: 1426593.00
  ValueRate: 22156.03 / second
  Rate: 7.70324 / second
  Percentiles: 1%=4.00; 5%=4.00; 10%=4.00; 20%=4.00; 50%=16.00; 80%=9307.00; 90%=9307.00; 95%=9307.00; 99%=9307.00
Metric: TransferFromServerTime
  TotalSamples: 495
  Accumulator: 01s021ms395.320us
  ValueRate: 016ms868.417us / second
  Rate: 7.69033 / second
  Percentiles: 1%=001ms273.826us; 5%=001ms484.632us; 10%=002ms585.834us; 20%=002ms676.570us; 50%=002ms879.289us; 80%=002ms043.648us; 90%=002ms137.945us; 95%=002ms214.404us; 99%=015ms688.982us
Metric: TransferToServerTime
  TotalSamples: 1046
  Accumulator: 21s218ms386.892us
  ValueRate: 300ms453.396us / second
  Rate: 15.293 / second
  Percentiles: 1%=001ms342.602us; 5%=001ms480.348us; 10%=002ms573.300us; 20%=002ms695.646us; 50%=002ms007.423us; 80%=024ms263.352us; 90%=093ms720.704us; 95%=095ms121.530us; 99%=097ms596.398us
Metric: TransferToServerTransformTime
  TotalSamples: 1046
  Accumulator: 318ms731.295us
  ValueRate: 004ms156.770us / second
  Rate: 15.293 / second
  Percentiles: 1%=088.272us; 5%=106.928us; 10%=114.379us; 20%=121.833us; 50%=146.826us; 80%=379.550us; 90%=559.672us; 95%=703.223us; 99%=001ms102.335us
Counter: CachedCompile
  Value: 488
Counter: CreateCompileHandles
  Value: 8
Counter: CreateDataHandles
  Value: 66980
Counter: CreateXlaTensor
  Value: 449211
Counter: DestroyDataHandles
  Value: 66302
Counter: DestroyXlaTensor
  Value: 448662
Counter: DeviceDataCacheMiss
  Value: 384
Counter: MarkStep
  Value: 125
Counter: ReleaseDataHandles
  Value: 66302
Counter: UncachedCompile
  Value: 8
Counter: XRTAllocateFromTensor_Empty
  Value: 41
Counter: XrtCompile_Empty
  Value: 1152
Counter: XrtExecuteChained_Empty
  Value: 1152
Counter: XrtExecute_Empty
  Value: 1152
Counter: XrtMemoryInfo_Empty
  Value: 1152
Counter: XrtRead_Empty
  Value: 1152
Counter: XrtReleaseAllocationHandle_Empty
  Value: 1152
Counter: XrtReleaseCompileHandle_Empty
  Value: 1152
Counter: XrtSessionCount
  Value: 11
Counter: XrtSubTuple_Empty
  Value: 1152
Counter: aten::_local_scalar_dense
  Value: 124
Counter: xla::_copy_from
  Value: 1620
Counter: xla::_log_softmax
  Value: 123
Counter: xla::_log_softmax_backward_data
  Value: 123
Counter: xla::_softmax
  Value: 2227
Counter: xla::_softmax_backward_data
  Value: 2214
Counter: xla::_unsafe_view
  Value: 16455
Counter: xla::add
  Value: 21327
Counter: xla::add_
  Value: 63103
Counter: xla::addcdiv_
  Value: 16236
Counter: xla::addcmul_
  Value: 16236
Counter: xla::all
  Value: 124
Counter: xla::arange_out
  Value: 124
Counter: xla::as_strided
  Value: 629
Counter: xla::bernoulli_
  Value: 7919
Counter: xla::bmm
  Value: 13310
Counter: xla::clone
  Value: 248
Counter: xla::constant_pad_nd
  Value: 1
Counter: xla::div
  Value: 4182
Counter: xla::div_
  Value: 7919
Counter: xla::embedding
  Value: 496
Counter: xla::embedding_dense_backward
  Value: 492
Counter: xla::empty
  Value: 9803
Counter: xla::empty_strided
  Value: 629
Counter: xla::eq
  Value: 124
Counter: xla::expand
  Value: 12968
Counter: xla::fill_
  Value: 247
Counter: xla::ge
  Value: 124
Counter: xla::index_select
  Value: 496
Counter: xla::le
  Value: 124
Counter: xla::masked_fill_
  Value: 124
Counter: xla::mean
  Value: 3959
Counter: xla::mm
  Value: 35863
Counter: xla::mul
  Value: 55939
Counter: xla::mul_
  Value: 32472
Counter: xla::nll_loss_backward
  Value: 123
Counter: xla::nll_loss_forward
  Value: 123
Counter: xla::permute
  Value: 494
Counter: xla::pow
  Value: 11831
Counter: xla::relu
  Value: 1485
Counter: xla::repeat
  Value: 124
Counter: xla::rsqrt
  Value: 3959
Counter: xla::rsub
  Value: 372
Counter: xla::select
  Value: 124
Counter: xla::slice
  Value: 1612
Counter: xla::sqrt
  Value: 16236
Counter: xla::squeeze
  Value: 246
Counter: xla::sum
  Value: 8118
Counter: xla::t
  Value: 47794
Counter: xla::threshold_backward
  Value: 1476
Counter: xla::transpose
  Value: 31061
Counter: xla::unsqueeze
  Value: 1612
Counter: xla::view
  Value: 97943
Counter: xla::zero_
  Value: 16616
Metric: XrtAllocateFromTensor
  TotalSamples: 17112
  Accumulator: 01m17s209ms365.449us
  Mean: 948.545us
  StdDev: 649.447us
  Rate: 42.1398 / second
  Percentiles: 25%=507.528us; 50%=722.895us; 80%=001ms298.039us; 90%=002ms953.707us; 95%=002ms433.085us; 99%=003ms050.874us
Metric: XrtCompile
  TotalSamples: 125
  Accumulator: 03m51s807ms386.002us
  Mean: 01s366ms459.088us
  StdDev: 04s107ms678.696us
  Rate: 0.058692 / second
  Percentiles: 25%=005ms611.938us; 50%=006ms915.717us; 80%=268ms934.186us; 90%=01s153ms804.716us; 95%=15s025ms837.806us; 99%=17s824ms114.282us
Metric: XrtExecute
  TotalSamples: 3223
  Accumulator: 03m24s554ms449.221us
  Mean: 050ms743.922us
  StdDev: 067ms037.853us
  Rate: 0.880515 / second
  Percentiles: 25%=001ms459.705us; 50%=002ms022.601us; 80%=098ms931.346us; 90%=172ms418.680us; 95%=173ms937.530us; 99%=173ms375.746us
Metric: XrtExecutorEvict
  TotalSamples: 0
  Accumulator: nanB
  Mean: nanB
  StdDev: nanB
  Percentiles: 
Metric: XrtReadLiteral
  TotalSamples: 1912
  Accumulator: 01s203ms512.251us
  Mean: 633.079us
  StdDev: 158.171us
  Rate: 0.836726 / second
  Percentiles: 25%=531.469us; 50%=624.089us; 80%=773.702us; 90%=825.615us; 95%=864.426us; 99%=939.246us
Metric: XrtReleaseAllocation
  TotalSamples: 20968
  Accumulator: 08s648ms839.434us
  Mean: 222.356us
  StdDev: 260.619us
  Rate: 125.843 / second
  Percentiles: 25%=031.432us; 50%=116.691us; 80%=382.645us; 90%=616.266us; 95%=804.075us; 99%=001ms106.211us
```

Is there anything else I can do to tackle this issue further?
