### ISSUE TITLE
on_save_checkoint never called

### ISSUE THREAD

**Issue by zhiyuanpeng** [PyTorchLightning/pytorch-lightning#9176]
## 🐛 Bug

I wrote a `Callback` class and found `on_save_checkpoint` had never been called

### To Reproduce

My callback class:
```
from pytorch_lightning.callbacks import Callback
from os.path import join
import torch
import os
import pytorch_lightning as pl
from typing import Dict, Any, Optional


class JitSave(Callback):

    def __init__(self):
        self.outputs = None
        self.n_dataloaders = None

    def on_save_checkpoint(
        self, trainer: 'pl.Trainer', pl_module: 'pl.LightningModule', checkpoint: Dict[
                str, Any]
    ) -> dict:
        # Torch.jit.save
        jit_model_dir = join(
            join(os.getcwd(), "checkpoints"), f"jit_{self.logger[0].version}" + "{}.pt"
        )
        torch.jit.save(self.model.cpu().to_torchscript(), jit_model_dir.format("cpu"))
        torch.jit.save(self.model.to_torchscript(), jit_model_dir.format("gpu"))
        print(f"torch.jit.save path :\n{jit_model_dir}")
        # return {"jitsave_path": jit_model_dir}
        return checkpoint

    def setup(self, trainer: 'pl.Trainer', pl_module: 'pl.LightningModule', stage: Optional[str] = None) -> None:
        self.n_dataloaders = len(pl_module.val_dataloader())

    def _reset(self):
        self.outputs = [[] for _ in range(self.n_dataloaders)]

    def on_epoch_start(self, trainer: 'pl.Trainer', pl_module: 'pl.LightningModule') -> None:
        self._reset()

    def on_validation_epoch_end(self, trainer: 'pl.Trainer', pl_module: 'pl.LightningModule') -> None:
        for dataloader_idx, output in enumerate(self.outputs):
            pass
```
`on_validation_epoch_end` works but on_save_checkpoint not.

This is my `ModelCheckpoint`:

```
model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: "val/f1" # name of the logged metric which determines when model isimproving
  mode: "max" # can be "max" or "min"
  save_top_k: 1 # save k best models (determined by above metric)
  save_last: False # additionaly always save model from last epoch
  verbose: False
  dirpath: "checkpoints/"
  filename: "epoch_{epoch:03d}"
  auto_insert_metric_name: False
  save_weights_only: True
```

Callbacks are passed to the trainer:

```
callbacks: List[Callback] = []
    if "callbacks" in config:
        for _, cb_conf in config.callbacks.items():
            if "_target_" in cb_conf:
                log.info(f"Instantiating callback <{cb_conf._target_}>")
                callbacks.append(hydra.utils.instantiate(cb_conf))
```

```
trainer: Trainer = hydra.utils.instantiate(
        config.trainer, callbacks=callbacks, logger=logger, _convert_="partial"
    )
```

### Expected behavior

`on_save_checkpoint` should be called.

### Environment

* CUDA:
        - GPU:
                - GeForce RTX 2080 Ti
        - available:         True
        - version:           10.2
* Packages:
        - numpy:             1.19.5
        - pyTorch_debug:     False
        - pyTorch_version:   1.9.0+cu102
        - pytorch-lightning: 1.4.2
        - tqdm:              4.62.1
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - ELF
        - processor:         x86_64
        - python:            3.8.10
        - version:           #60~20.04.1-Ubuntu SMP Thu May 6 09:52:46 UTC 2021
