### ISSUE TITLE
Trainer doesn't save the model correctly if max_steps is a small value (<5)

### ISSUE THREAD

**Issue by zzomg** [PyTorchLightning/pytorch-lightning#9348]
Hi 👋 I'm trying to implement an algorithm, where at some point I have to train model for 1 step only. I'm loading model weights from a pre-trained checkpoint via: 

`ckpt = torch.load(ckpt_path)`
`model.load_state_dict(ckpt['state_dict'], strict=False)`

The size of this pre-trained checkpoint is 367040971 bytes. However, after training the model for 1 step and saving it with `trainer.save_checkpoint("model.ckpt")`, the size is reduced to only 122494693 bytes (~3 times less), which is strange. The same situation repeats when max_steps=2. But when I set max_steps to somewhat bigger value (5, 10 etc), it's saved normally (around 367040971 bytes). 

I was wondering whether it's a normal behavior, or something is wrong.

The model I'm trying to train is Conformer from NVIDIA NeMo, and I got this bug on both one GPU and multiple GPUs.

**Environment:**

* CUDA:
        - GPU:
                - NVIDIA GeForce RTX 3090
                - NVIDIA GeForce RTX 3090
        - available:         True
        - version:           11.0
* Packages:
        - numpy:             1.21.1
        - pyTorch_debug:     True
        - pyTorch_version:   1.7.0+cu110
        - pytorch-lightning: 1.3.7post0
        - tqdm:              4.61.2
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - ELF
        - processor:         x86_64
        - python:            3.8.10

+ NVIDIA NeMo ver. 1.1.0

These are the trainer setting I use (I got config from here https://github.com/NVIDIA/NeMo/blob/main/examples/asr/conf/conformer/conformer_ctc_char.yaml and modified it for my needs):
```
trainer:
  gpus: 2 # number of GPUs, -1 would use all available GPUs
  num_nodes: 1
  max_epochs: null
  max_steps: null # I set it in the code, not here
  val_check_interval: 1.0 # Set to 0.25 to check 4 times per epoch, or an int for number of iterations
  accelerator: ddp
  accumulate_grad_batches: 1
  gradient_clip_val: 0.0
  amp_level: O1 # O1/O2 for mixed precision
  precision: 16 # Should be set to 16 for O1 and O2 to enable the AMP.
  log_every_n_steps: 10  # Interval of logging.
  progress_bar_refresh_rate: 10
  limit_train_batches: 0.01
  limit_val_batches: 0.15
  limit_test_batches: 0.15 
  resume_from_checkpoint: null # The path to a checkpoint file to continue the training, restores the whole state including the epoch, step, LR schedulers, apex, etc.
  num_sanity_val_steps: 0 # number of steps to perform validation steps for sanity check the validation process before starting the training, setting to 0 disables it
  check_val_every_n_epoch: 1 # number of evaluations on validation every n epochs
  sync_batchnorm: false
  checkpoint_callback: false  # Provided by exp_manager
  logger: false  # Provided by exp_manager
```

To reproduce:
```
import os
import json
import argparse
from omegaconf import OmegaConf

import torch
import nemo.collections.asr as nemo_asr
import pytorch_lightning as pl

def load_config(config_path):
    config = OmegaConf.load(config_path)
    config = OmegaConf.to_container(config, resolve=True)
    config = OmegaConf.create(config)
    return config
    
config = load_config(config_path)

config.model.train_ds.manifest_filepath = /path/to/manifest
config.model.validation_ds.manifest_filepath = /path/to/manifest
config.model.test_ds.manifest_filepath = /path/to/manifest
config.trainer.max_steps = 1 # or 2
config.trainer.gpus = 1 # or 2

trainer = pl.Trainer(**config.trainer)

ckpt_path = /path/to/ckpt
ckpt = torch.load(ckpt_path)

model = nemo_asr.models.EncDecCTCModel(cfg=config.model, trainer=trainer)
model.load_state_dict(ckpt['state_dict'], strict=False)

trainer.fit(model) 
trainer.save_checkpoint("model.ckpt")
trainer.test("model.ckpt")
```
