### ISSUE TITLE
Can't resume training from checkpoint

### ISSUE THREAD

**Issue by p1x31** [PyTorchLightning/pytorch-lightning#9852]
## 🐛 Bug

When trying to resume from the checkpoint I'm getting this error. Pretty sure optimizer and scheduler states are saved
```
....
File "/home/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/optim/_functional.py", line 84, in adam

exp_avg.mul_(beta1).add_(grad, alpha=1 - beta1)
RuntimeError: The size of tensor a (200) must match the size of tensor b (5) at non-singleton dimension 3

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

```

### To Reproduce

it is a massive image to text model
```python
def train(cfg: DictConfig) -> None:
    # BUG: pytorch lightning fails on non-existent checkpoint
    resume_from_checkpoint = cfg.train.resume_from_checkpoint
    if (resume_from_checkpoint is not None) and (not os.path.exists(resume_from_checkpoint)):
        logger.warning(f"Not using missing checkpoint {resume_from_checkpoint}, starting from scratch...")
        resume_from_checkpoint = None

    callbacks = [instantiate(x) for x in cfg.train.callbacks.values()]
    plugins = [instantiate(x) for x in cfg.train.plugins.values()]
    trainer = pl.Trainer(
        **cfg.train.trainer_params,
        plugins=plugins,
        callbacks=callbacks,
        logger=instantiate(cfg.train.logger),
        profiler="simple",
        resume_from_checkpoint=resume_from_checkpoint
    )

    model = I2T(config=cfg)
    if resume_from_checkpoint is not None:
        logger.info(f"Resuming training from checkpoint {resume_from_checkpoint}")
    else:
        model.init_pretrain_modules()

    train_dataloader, val_dataloader = get_dataloaders(
        **cfg.data,
        batch_size=cfg.train.batch_size,
    )

    trainer.fit(train_dataloaders=train_dataloader, val_dataloaders=val_dataloader, model=model)
```
cfg file:
```yaml
batch_size: 128
trainer_params:
  limit_train_batches: 1.0
  gpus: 1
  accelerator: ddp
  precision: 16
  log_every_n_steps: 10
  flush_logs_every_n_steps: 100
  checkpoint_callback: true
  weights_summary: full
  check_val_every_n_epoch: 1
  val_check_interval: 0.5
  num_sanity_val_steps: 8
  terminate_on_nan: True
resume_from_checkpoint: ${ckpt_directory}/lastm.ckpt
plugins: {}
callbacks:
  lr_logging: pytorch_lightning.callbacks.LearningRateMonitor
  ckpt:
    cls: pytorch_lightning.callbacks.ModelCheckpoint
    args:
      dirpath: ${ckpt_directory}
      every_n_train_steps: 200
```

### Expected behaviour

Resume from checkpoint (start of the epoch or last step saved)

### Environment

- PyTorch Lightning Version (e.g., 1.3.0): 1.4.9
- PyTorch Version (e.g., 1.8): 1.9
- Python version: 3.8
- OS (e.g., Linux): 20.04
- CUDA/cuDNN version: 11.3
- GPU models and configuration: rtx 2080ti
- How you installed PyTorch (`conda`, `pip`, source): conda
- If compiling from source, the output of `torch.__config__.show()`:
- Any other relevant information:

### Additional context

Does it have to be manual saving with accelerators?
